// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.ComponentFns;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>ExecutionManager</b><br>
 * Generated     : <b>2017/07/19 4:19:54 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  July 19, 2017
 * @author UI171010
 */
public abstract class ExecutionManagerHelper extends RationalTestScript
{
	/**
	 * htmlBrowser: with default state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser() 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"));
	}
	/**
	 * htmlBrowser: with specific test context and state.
	 *		.class : Html.HtmlBrowser
	 * 		.browserName : MS Internet Explorer
	 * 		.processName : iexplore.exe
	 */
	protected BrowserTestObject browser_htmlBrowser(TestObject anchor, long flags) 
	{
		return new BrowserTestObject(
                        getMappedTestObject("browser_htmlBrowser"), anchor, flags);
	}
	
	/**
	 * EDSNGatewayTest: with default state.
	 *		.title : RegularExpression(.*EDSN.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject edsnHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("edsnHtmlDocument"));
	}
	/**
	 * EDSNGatewayTest: with specific test context and state.
	 *		.title : RegularExpression(.*EDSN.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject edsnHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("edsnHtmlDocument"), anchor, flags);
	}
	
	/**
	 * MijnEnergiedirectNl: with default state.
	 *		.title : .*Mijn energiedirect.*
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject mijnEDHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mijnEDHtmlDocument"));
	}
	/**
	 * MijnEnergiedirectNl: with specific test context and state.
	 *		.title : .*Mijn energiedirect.*
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject mijnEDHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mijnEDHtmlDocument"), anchor, flags);
	}
	
	/**
	 * MijnEssent: with default state.
	 *		.title : RegularExpression(.*Mijn Essent.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : 
	 */
	protected DocumentTestObject mijnEssentHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mijnEssentHtmlDocument"));
	}
	/**
	 * MijnEssent: with specific test context and state.
	 *		.title : RegularExpression(.*Mijn Essent.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : 
	 */
	protected DocumentTestObject mijnEssentHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mijnEssentHtmlDocument"), anchor, flags);
	}
	
	/**
	 * Registreren: with default state.
	 *		.title : RegularExpression(.*MPR .*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject mprHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mprHtmlDocument"));
	}
	/**
	 * Registreren: with specific test context and state.
	 *		.title : RegularExpression(.*MPR .*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject mprHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("mprHtmlDocument"), anchor, flags);
	}
	
	/**
	 * WorkItem50835216678AV6CSRVCTRTWAIT4CRT: with default state.
	 *		.title : RegularExpression(Work Item: .* - .* - .* - .*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http(s|)://.*(TIBCO|tibco).*essent.*\.*TIBCOiPClnt/.*)
	 */
	protected DocumentTestObject placeHolderDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("placeHolderDocument"));
	}
	/**
	 * WorkItem50835216678AV6CSRVCTRTWAIT4CRT: with specific test context and state.
	 *		.title : RegularExpression(Work Item: .* - .* - .* - .*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression(http(s|)://.*(TIBCO|tibco).*essent.*\.*TIBCOiPClnt/.*)
	 */
	protected DocumentTestObject placeHolderDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("placeHolderDocument"), anchor, flags);
	}
	
	/**
	 * TIBCOIProcessWorkspaceBrowserLogin: with default state.
	 *		.title : RegularExpression(.*iProcess.*|.*Work Item.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject tibcoHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("tibcoHtmlDocument"));
	}
	/**
	 * TIBCOIProcessWorkspaceBrowserLogin: with specific test context and state.
	 *		.title : RegularExpression(.*iProcess.*|.*Work Item.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject tibcoHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("tibcoHtmlDocument"), anchor, flags);
	}
	
	/**
	 * Logon: with default state.
	 *		.title : RegularExpression(.*SAP.*Logon.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject webUIHtmlDocument() 
	{
		return new DocumentTestObject(
                        getMappedTestObject("webUIHtmlDocument"));
	}
	/**
	 * Logon: with specific test context and state.
	 *		.title : RegularExpression(.*SAP.*Logon.*)
	 * 		.class : Html.HtmlDocument
	 * 		.url : RegularExpression()
	 */
	protected DocumentTestObject webUIHtmlDocument(TestObject anchor, long flags) 
	{
		return new DocumentTestObject(
                        getMappedTestObject("webUIHtmlDocument"), anchor, flags);
	}
	
	

	protected ExecutionManagerHelper()
	{
		setScriptName("ComponentFns.ExecutionManager");
	}
	
}

