// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.Classes;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>SAP</b><br>
 * Generated     : <b>2017/04/20 6:52:16 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  April 20, 2017
 * @author UI171010
 */
public abstract class SAPHelper extends RationalTestScript
{
	/**
	 * Back: with default state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_back() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_back"));
	}
	/**
	 * Back: with specific test context and state.
	 *		Name : btn[3]
	 * 		Id : /btn[3]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_back(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_back"), anchor, flags);
	}
	
	/**
	 * Cancel: with default state.
	 *		Name : btn[12]
	 * 		Id : /btn[12]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_cancel() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_cancel"));
	}
	/**
	 * Cancel: with specific test context and state.
	 *		Name : btn[12]
	 * 		Id : /btn[12]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_cancel(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_cancel"), anchor, flags);
	}
	
	/**
	 * Continue: with default state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_continue() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_continue"));
	}
	/**
	 * Continue: with specific test context and state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_continue(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_continue"), anchor, flags);
	}
	
	/**
	 * Continue: with default state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_continue2() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_continue2"));
	}
	/**
	 * Continue: with specific test context and state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_continue2(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_continue2"), anchor, flags);
	}
	
	/**
	 * Enter: with default state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_enter() 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_enter"));
	}
	/**
	 * Enter: with specific test context and state.
	 *		Name : btn[0]
	 * 		Id : /btn[0]
	 * 		.class : GuiButton
	 */
	protected SAPGuiToggleTestObject button_enter(TestObject anchor, long flags) 
	{
		return new SAPGuiToggleTestObject(
                        getMappedTestObject("button_enter"), anchor, flags);
	}
	
	/**
	 * okcd: with default state.
	 *		Name : okcd
	 * 		Id : /okcd
	 * 		.class : GuiOkCodeField
	 */
	protected SAPGuiTextTestObject comboBox_okcd() 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("comboBox_okcd"));
	}
	/**
	 * okcd: with specific test context and state.
	 *		Name : okcd
	 * 		Id : /okcd
	 * 		.class : GuiOkCodeField
	 */
	protected SAPGuiTextTestObject comboBox_okcd(TestObject anchor, long flags) 
	{
		return new SAPGuiTextTestObject(
                        getMappedTestObject("comboBox_okcd"), anchor, flags);
	}
	
	/**
	 * Copyright: with default state.
	 *		Name : wnd[1]
	 * 		.connectionNumber : 0
	 * 		Text : Copyright
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_copyright() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_copyright"));
	}
	/**
	 * Copyright: with specific test context and state.
	 *		Name : wnd[1]
	 * 		.connectionNumber : 0
	 * 		Text : Copyright
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_copyright(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_copyright"), anchor, flags);
	}
	
	/**
	 * Information: with default state.
	 *		Name : wnd[1]
	 * 		.connectionNumber : 0
	 * 		Text : Information
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_information() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_information"));
	}
	/**
	 * Information: with specific test context and state.
	 *		Name : wnd[1]
	 * 		.connectionNumber : 0
	 * 		Text : Information
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_information(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_information"), anchor, flags);
	}
	
	/**
	 * SystemMessages: with default state.
	 *		Name : wnd[1]
	 * 		Text : RegularExpression(.*)
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_systemMessages() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_systemMessages"));
	}
	/**
	 * SystemMessages: with specific test context and state.
	 *		Name : wnd[1]
	 * 		Text : RegularExpression(.*)
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[1]
	 * 		.class : GuiModalWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject dialog_systemMessages(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("dialog_systemMessages"), anchor, flags);
	}
	
	/**
	 * usr: with default state.
	 *		Name : usr
	 * 		Id : /usr
	 * 		.class : GuiUserArea
	 */
	protected SAPGuiUserAreaTestObject panel_usr() 
	{
		return new SAPGuiUserAreaTestObject(
                        getMappedTestObject("panel_usr"));
	}
	/**
	 * usr: with specific test context and state.
	 *		Name : usr
	 * 		Id : /usr
	 * 		.class : GuiUserArea
	 */
	protected SAPGuiUserAreaTestObject panel_usr(TestObject anchor, long flags) 
	{
		return new SAPGuiUserAreaTestObject(
                        getMappedTestObject("panel_usr"), anchor, flags);
	}
	
	/**
	 * SAPLogon720: with default state.
	 *		.text : RegularExpression(SAP Logon 7(2|3|4)0)
	 * 		.class : #32770
	 * 		.processName : saplogon.exe
	 * 		.name : RegularExpression(SAP Logon 7(2|3|4)0)
	 */
	protected TopLevelSubitemTestObject sapLogon720window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sapLogon720window"));
	}
	/**
	 * SAPLogon720: with specific test context and state.
	 *		.text : RegularExpression(SAP Logon 7(2|3|4)0)
	 * 		.class : #32770
	 * 		.processName : saplogon.exe
	 * 		.name : RegularExpression(SAP Logon 7(2|3|4)0)
	 */
	protected TopLevelSubitemTestObject sapLogon720window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("sapLogon720window"), anchor, flags);
	}
	
	/**
	 * SAP: with default state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap() 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap"));
	}
	/**
	 * SAP: with specific test context and state.
	 *		Name : wnd[0]
	 * 		Text : SAP
	 * 		.connectionNumber : 0
	 * 		Id : /wnd[0]
	 * 		.class : GuiMainWindow
	 * 		.sessionNumber : 0
	 * 		.processName : saplogon.exe
	 */
	protected SAPTopLevelTestObject window_sap(TestObject anchor, long flags) 
	{
		return new SAPTopLevelTestObject(
                        getMappedTestObject("window_sap"), anchor, flags);
	}
	
	

	protected SAPHelper()
	{
		setScriptName("Classes.SAP");
	}
	
}

